// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mosaic.Data;

#nullable disable

namespace Mosaic.Data.Migrations
{
    [DbContext(typeof(MosaicDbContext))]
    [Migration("20260601103001_AddAchievements")]
    partial class AddAchievements
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("Mosaic.Models.Achievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Hidden")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IconLockedPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("IconUnlockedPath")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsManualDefinition")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsManualUnlock")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("UnlockedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameId", "ApiName")
                        .IsUnique();

                    b.ToTable("Achievements");
                });

            modelBuilder.Entity("Mosaic.Models.Artwork", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsManualOverride")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocalPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("SourceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameId", "Kind");

                    b.ToTable("Artwork");
                });

            modelBuilder.Entity("Mosaic.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AchievementSource")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AchievementTrackingEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<DateTimeOffset>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutablePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LaunchArguments")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RealExecutableName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SteamAppId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorkingDirectory")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExecutablePath")
                        .IsUnique();

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Mosaic.Models.PlaySession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EndedAt");

                    b.HasIndex("GameId");

                    b.ToTable("PlaySessions");
                });

            modelBuilder.Entity("Mosaic.Models.Achievement", b =>
                {
                    b.HasOne("Mosaic.Models.Game", "Game")
                        .WithMany("Achievements")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Mosaic.Models.Artwork", b =>
                {
                    b.HasOne("Mosaic.Models.Game", "Game")
                        .WithMany("Artwork")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Mosaic.Models.PlaySession", b =>
                {
                    b.HasOne("Mosaic.Models.Game", "Game")
                        .WithMany("Sessions")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Mosaic.Models.Game", b =>
                {
                    b.Navigation("Achievements");

                    b.Navigation("Artwork");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
